const fs = require('fs');

const recordings = [
  {
    id: "1",
    type: "audio/mpeg",
    filePath: "/recordings/1a_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "2",
    type: "audio/mpeg",
    filePath: "/recordings/1a_baritono1.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "3",
    type: "audio/mpeg",
    filePath: "/recordings/1a_baritono2.mp3",
    voiceType: "1",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "4",
    type: "audio/mpeg",
    filePath: "/recordings/1a_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "5",
    type: "audio/mpeg",
    filePath: "/recordings/1a_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "6",
    type: "audio/mpeg",
    filePath: "/recordings/1b_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "7",
    type: "audio/mpeg",
    filePath: "/recordings/1b_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "8",
    type: "audio/mpeg",
    filePath: "/recordings/1b_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "9",
    type: "audio/mpeg",
    filePath: "/recordings/1b_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "10",
    type: "audio/mpeg",
    filePath: "/recordings/2a_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "11",
    type: "audio/mpeg",
    filePath: "/recordings/2a_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "12",
    type: "audio/mpeg",
    filePath: "/recordings/2b_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "13",
    type: "audio/mpeg",
    filePath: "/recordings/2b_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "14",
    type: "audio/mpeg",
    filePath: "/recordings/2b_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "15",
    type: "audio/mpeg",
    filePath: "/recordings/3_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "16",
    type: "audio/mpeg",
    filePath: "/recordings/3_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "17",
    type: "audio/mpeg",
    filePath: "/recordings/4a_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "18",
    type: "audio/mpeg",
    filePath: "/recordings/4a_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "19",
    type: "audio/mpeg",
    filePath: "/recordings/4b_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "20",
    type: "audio/mpeg",
    filePath: "/recordings/4b_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "21",
    type: "audio/mpeg",
    filePath: "/recordings/5_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "22",
    type: "audio/mpeg",
    filePath: "/recordings/5_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "23",
    type: "audio/mpeg",
    filePath: "/recordings/5_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "24",
    type: "audio/mpeg",
    filePath: "/recordings/5_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "25",
    type: "audio/mpeg",
    filePath: "/recordings/6_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "26",
    type: "audio/mpeg",
    filePath: "/recordings/6_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "27",
    type: "audio/mpeg",
    filePath: "/recordings/7hidas_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "28",
    type: "audio/mpeg",
    filePath: "/recordings/7hidas_baritono1.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "29",
    type: "audio/mpeg",
    filePath: "/recordings/7hidas_baritono2.mp3",
    voiceType: "1",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "30",
    type: "audio/mpeg",
    filePath: "/recordings/7hidas_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "31",
    type: "audio/mpeg",
    filePath: "/recordings/7hidas_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "32",
    type: "audio/mpeg",
    filePath: "/recordings/7nopea_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "33",
    type: "audio/mpeg",
    filePath: "/recordings/7nopea_baritono1.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "34",
    type: "audio/mpeg",
    filePath: "/recordings/7nopea_baritono2.mp3",
    voiceType: "1",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "35",
    type: "audio/mpeg",
    filePath: "/recordings/7nopea_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "36",
    type: "audio/mpeg",
    filePath: "/recordings/7nopea_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "37",
    type: "audio/mpeg",
    filePath: "/recordings/8a_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "38",
    type: "audio/mpeg",
    filePath: "/recordings/8a_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "39",
    type: "audio/mpeg",
    filePath: "/recordings/8a_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "40",
    type: "audio/mpeg",
    filePath: "/recordings/8a_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "41",
    type: "audio/mpeg",
    filePath: "/recordings/8a_tenor.mp3",
    voiceType: "3",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "42",
    type: "audio/mpeg",
    filePath: "/recordings/8b_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "43",
    type: "audio/mpeg",
    filePath: "/recordings/8b_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "44",
    type: "audio/mpeg",
    filePath: "/recordings/8b_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "45",
    type: "audio/mpeg",
    filePath: "/recordings/8b_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "46",
    type: "audio/mpeg",
    filePath: "/recordings/8b_tenor.mp3",
    voiceType: "3",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "47",
    type: "audio/mpeg",
    filePath: "/recordings/9a_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "48",
    type: "audio/mpeg",
    filePath: "/recordings/9a_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "49",
    type: "audio/mpeg",
    filePath: "/recordings/9a_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "50",
    type: "audio/mpeg",
    filePath: "/recordings/9a_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "51",
    type: "audio/mpeg",
    filePath: "/recordings/9b_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "52",
    type: "audio/mpeg",
    filePath: "/recordings/9b_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "53",
    type: "audio/mpeg",
    filePath: "/recordings/9b_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "54",
    type: "audio/mpeg",
    filePath: "/recordings/9b_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "55",
    type: "audio/mpeg",
    filePath: "/recordings/10a_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "56",
    type: "audio/mpeg",
    filePath: "/recordings/10a_tenor.mp3",
    voiceType: "3",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "57",
    type: "audio/mpeg",
    filePath: "/recordings/10b_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "58",
    type: "audio/mpeg",
    filePath: "/recordings/10b_tenor.mp3",
    voiceType: "3",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "59",
    type: "audio/mpeg",
    filePath: "/recordings/11_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "60",
    type: "audio/mpeg",
    filePath: "/recordings/11_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "61",
    type: "audio/mpeg",
    filePath: "/recordings/11_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "62",
    type: "audio/mpeg",
    filePath: "/recordings/11_tenor.mp3",
    voiceType: "3",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "63",
    type: "audio/mpeg",
    filePath: "/recordings/12_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "64",
    type: "audio/mpeg",
    filePath: "/recordings/12_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "65",
    type: "audio/mpeg",
    filePath: "/recordings/12_tenor.mp3",
    voiceType: "3",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "66",
    type: "audio/mpeg",
    filePath: "/recordings/13a_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "67",
    type: "audio/mpeg",
    filePath: "/recordings/13a_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "68",
    type: "audio/mpeg",
    filePath: "/recordings/13a_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "69",
    type: "audio/mpeg",
    filePath: "/recordings/13b_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "70",
    type: "audio/mpeg",
    filePath: "/recordings/13b_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "71",
    type: "audio/mpeg",
    filePath: "/recordings/13b_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "72",
    type: "audio/mpeg",
    filePath: "/recordings/14_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "73",
    type: "audio/mpeg",
    filePath: "/recordings/14_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "74",
    type: "audio/mpeg",
    filePath: "/recordings/14_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "75",
    type: "audio/mpeg",
    filePath: "/recordings/15_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "76",
    type: "audio/mpeg",
    filePath: "/recordings/15_baritono.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "77",
    type: "audio/mpeg",
    filePath: "/recordings/15_mezzo.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "78",
    type: "audio/mpeg",
    filePath: "/recordings/15_soprano.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "79",
    type: "audio/mpeg",
    filePath: "/recordings/aquecimento_01.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "80",
    type: "audio/mpeg",
    filePath: "/recordings/aquecimento_02.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "81",
    type: "audio/mpeg",
    filePath: "/recordings/aquecimento_03.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "82",
    type: "audio/mpeg",
    filePath: "/recordings/1a_contralto_accompaniment.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "83",
    type: "audio/mpeg",
    filePath: "/recordings/1a_baritono1_accompaniment.mp3",
    voiceType: "2",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "84",
    type: "audio/mpeg",
    filePath: "/recordings/1a_baritono2_accompaniment.mp3",
    voiceType: "1",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "85",
    type: "audio/mpeg",
    filePath: "/recordings/1a_mezzo_accompaniment.mp3",
    voiceType: "5",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "86",
    type: "audio/mpeg",
    filePath: "/recordings/1a_soprano_accompaniment.mp3",
    voiceType: "6",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "87",
    type: "audio/mpeg",
    filePath: "/recordings/belting_01.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "88",
    type: "audio/mpeg",
    filePath: "/recordings/belting_02.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "89",
    type: "audio/mpeg",
    filePath: "/recordings/belting_03.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "90",
    type: "audio/mpeg",
    filePath: "/recordings/belting_04.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "91",
    type: "audio/mpeg",
    filePath: "/recordings/belting_05.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "92",
    type: "audio/mpeg",
    filePath: "/recordings/belting_06.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: true,
  },
  {
    id: "93",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n01_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "94",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n02_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "95",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n03_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "96",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n04_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "97",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n05_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "98",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n06_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "99",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n07_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "100",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n08_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "101",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n09_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "102",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n10_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "103",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n11_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "104",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n12_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "105",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n13_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "106",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n14_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "107",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n15_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "108",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n17_allegro_molto_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "109",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n18_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "110",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n19_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "111",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n21_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "112",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n22_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "113",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n23_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "114",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n24_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "115",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n16_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "116",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n20_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "117",
    type: "audio/mpeg",
    filePath: "/recordings/aquecimento_diafragma_controle_do_ar.mp3",
    voiceType: "0",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "118",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n01_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "119",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n02_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "120",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n03_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "121",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n04_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "122",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n05_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "124",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n06_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "125",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n07_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "126",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n08_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "127",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n09_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "128",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n10_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "129",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n11_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "130",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n12_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "131",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n13_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "132",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n14_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "133",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n15_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "134",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n16_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "135",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n17_allegro_molto_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "136",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n17_moderato_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "137",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n18_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "138",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n19_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "139",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n20_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "140",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n21_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "141",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n22_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "142",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n23_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "143",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n24_contralto.mp3",
    voiceType: "4",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "145",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n01_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "146",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n02_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "147",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n03_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "148",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n04_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "149",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n05_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "150",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n06_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "151",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n07_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "152",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n08_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "153",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n09_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "154",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n10_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "155",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n11_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "156",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n12_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "157",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n13_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "158",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n14_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "159",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n15_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "160",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n16_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "161",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n17_allegro_molto_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "162",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n17_moderato_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "163",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n18_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "164",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n19_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "165",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n20_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "166",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n21_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "167",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n22_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "168",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n23_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "169",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n24_baritono_baixo.mp3",
    voiceType: "8",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
  {
    id: "170",
    type: "audio/mpeg",
    filePath: "/recordings/panofka_op81_24_vocalizes_n17_moderato_soprano_mezzo_tenor.mp3",
    voiceType: "7",
    speedId: "1",
    accompaniment: true,
    vocals: false,
  },
];

let recordingsCSV = 'id,file_type,file_path,has_instruments,has_vocals';
let recordingVoiceRelationTypesCSV = 'recording_id,voice_type_id';

recordings.forEach((recording, id) => {
  const _id = id+1
  recordingsCSV += `\n${_id},${recording.type},${recording.filePath},${recording.accompaniment},${recording.vocals}`;
  switch(recording.voiceType) {
    case '0':
      recordingVoiceRelationTypesCSV += `\n${_id},1`
      recordingVoiceRelationTypesCSV += `\n${_id},2`
      recordingVoiceRelationTypesCSV += `\n${_id},3`
      recordingVoiceRelationTypesCSV += `\n${_id},4`
      recordingVoiceRelationTypesCSV += `\n${_id},5`
      recordingVoiceRelationTypesCSV += `\n${_id},6`
      break;
    case '7':
      recordingVoiceRelationTypesCSV += `\n${_id},6`
      recordingVoiceRelationTypesCSV += `\n${_id},5`
      recordingVoiceRelationTypesCSV += `\n${_id},3`
      break;
    case '8':
      recordingVoiceRelationTypesCSV += `\n${_id},1`
      recordingVoiceRelationTypesCSV += `\n${_id},2`
      break;
    default:
      recordingVoiceRelationTypesCSV += `\n${_id},${recording.voiceType}`
  }
});

fs.writeFileSync('recordings.csv', recordingsCSV);
fs.writeFileSync('recordings_voice_types.csv', recordingVoiceRelationTypesCSV);

module.exports = recordings;

/* export default recordings; */