const voiceTypes = [
  {
    id: 1,
    title: "Baixo",
  },
  {
    id: 2,
    title: "Barítono",
  },
  {
    id: 3,
    title: "Tenor",
  },
  {
    id: 4,
    title: "Contralto",
  },
  {
    id: 5,
    title: "Mezzo-Soprano",
  },
  {
    id: 6,
    title: "Soprano",
  },
];

const voiceTypeOrderById = [6, 5, 4, 3, 2, 1];

const speeds = [
  {
    id: 1,
    title: "Normal",
  },
  {
    id: 2,
    title: "Rápido",
  },
];

const recordings = [
  {
    id: 1,
    type: "audio/mpeg",
    filePath: "/songs/1a_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 2,
    type: "audio/mpeg",
    filePath: "/songs/1a_baritoni1.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 3,
    type: "audio/mpeg",
    filePath: "/songs/1a_baritoni2.mp3",
    voiceType: 1,
    speedId: 1,
  },
  {
    id: 4,
    type: "audio/mpeg",
    filePath: "/songs/1a_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 5,
    type: "audio/mpeg",
    filePath: "/songs/1a_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 6,
    type: "audio/mpeg",
    filePath: "/songs/1b_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 7,
    type: "audio/mpeg",
    filePath: "/songs/1b_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 8,
    type: "audio/mpeg",
    filePath: "/songs/1b_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 9,
    type: "audio/mpeg",
    filePath: "/songs/1b_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 10,
    type: "audio/mpeg",
    filePath: "/songs/2a_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 11,
    type: "audio/mpeg",
    filePath: "/songs/2a_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 12,
    type: "audio/mpeg",
    filePath: "/songs/2b_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 13,
    type: "audio/mpeg",
    filePath: "/songs/2b_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 14,
    type: "audio/mpeg",
    filePath: "/songs/2b_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 15,
    type: "audio/mpeg",
    filePath: "/songs/3_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 16,
    type: "audio/mpeg",
    filePath: "/songs/3_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 17,
    type: "audio/mpeg",
    filePath: "/songs/4a_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 18,
    type: "audio/mpeg",
    filePath: "/songs/4a_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 19,
    type: "audio/mpeg",
    filePath: "/songs/4b_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 20,
    type: "audio/mpeg",
    filePath: "/songs/4b_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 21,
    type: "audio/mpeg",
    filePath: "/songs/5_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 22,
    type: "audio/mpeg",
    filePath: "/songs/5_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 23,
    type: "audio/mpeg",
    filePath: "/songs/5_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 24,
    type: "audio/mpeg",
    filePath: "/songs/5_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 25,
    type: "audio/mpeg",
    filePath: "/songs/6_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 26,
    type: "audio/mpeg",
    filePath: "/songs/6_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 27,
    type: "audio/mpeg",
    filePath: "/songs/7hidas_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 28,
    type: "audio/mpeg",
    filePath: "/songs/7hidas_baritoni1.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 29,
    type: "audio/mpeg",
    filePath: "/songs/7hidas_baritoni2.mp3",
    voiceType: 1,
    speedId: 1,
  },
  {
    id: 30,
    type: "audio/mpeg",
    filePath: "/songs/7hidas_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 31,
    type: "audio/mpeg",
    filePath: "/songs/7hidas_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 32,
    type: "audio/mpeg",
    filePath: "/songs/7nopea_altto.mp3",
    voiceType: 4,
    speedId: 2,
  },
  {
    id: 33,
    type: "audio/mpeg",
    filePath: "/songs/7nopea_baritoni1.mp3",
    voiceType: 2,
    speedId: 2,
  },
  {
    id: 34,
    type: "audio/mpeg",
    filePath: "/songs/7nopea_baritoni2.mp3",
    voiceType: 1,
    speedId: 2,
  },
  {
    id: 35,
    type: "audio/mpeg",
    filePath: "/songs/7nopea_mezzo.mp3",
    voiceType: 5,
    speedId: 2,
  },
  {
    id: 36,
    type: "audio/mpeg",
    filePath: "/songs/7nopea_sopraano.mp3",
    voiceType: 6,
    speedId: 2,
  },
  {
    id: 37,
    type: "audio/mpeg",
    filePath: "/songs/8a_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 38,
    type: "audio/mpeg",
    filePath: "/songs/8a_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 39,
    type: "audio/mpeg",
    filePath: "/songs/8a_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 40,
    type: "audio/mpeg",
    filePath: "/songs/8a_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 41,
    type: "audio/mpeg",
    filePath: "/songs/8a_tenori.mp3",
    voiceType: 3,
    speedId: 1,
  },
  {
    id: 42,
    type: "audio/mpeg",
    filePath: "/songs/8b_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 43,
    type: "audio/mpeg",
    filePath: "/songs/8b_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 44,
    type: "audio/mpeg",
    filePath: "/songs/8b_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 45,
    type: "audio/mpeg",
    filePath: "/songs/8b_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 46,
    type: "audio/mpeg",
    filePath: "/songs/8b_tenori.mp3",
    voiceType: 3,
    speedId: 1,
  },
  {
    id: 47,
    type: "audio/mpeg",
    filePath: "/songs/9a_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 48,
    type: "audio/mpeg",
    filePath: "/songs/9a_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 49,
    type: "audio/mpeg",
    filePath: "/songs/9a_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 50,
    type: "audio/mpeg",
    filePath: "/songs/9a_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 51,
    type: "audio/mpeg",
    filePath: "/songs/9b_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 52,
    type: "audio/mpeg",
    filePath: "/songs/9b_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 53,
    type: "audio/mpeg",
    filePath: "/songs/9b_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 54,
    type: "audio/mpeg",
    filePath: "/songs/9b_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 55,
    type: "audio/mpeg",
    filePath: "/songs/10a_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 56,
    type: "audio/mpeg",
    filePath: "/songs/10a_tenori.mp3",
    voiceType: 3,
    speedId: 1,
  },
  {
    id: 57,
    type: "audio/mpeg",
    filePath: "/songs/10b_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 58,
    type: "audio/mpeg",
    filePath: "/songs/10b_tenori.mp3",
    voiceType: 3,
    speedId: 1,
  },
  {
    id: 59,
    type: "audio/mpeg",
    filePath: "/songs/11_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 60,
    type: "audio/mpeg",
    filePath: "/songs/11_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 61,
    type: "audio/mpeg",
    filePath: "/songs/11_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 62,
    type: "audio/mpeg",
    filePath: "/songs/11_tenori.mp3",
    voiceType: 3,
    speedId: 1,
  },
  {
    id: 63,
    type: "audio/mpeg",
    filePath: "/songs/12_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 64,
    type: "audio/mpeg",
    filePath: "/songs/12_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 65,
    type: "audio/mpeg",
    filePath: "/songs/12_tenori.mp3",
    voiceType: 3,
    speedId: 1,
  },
  {
    id: 66,
    type: "audio/mpeg",
    filePath: "/songs/13a_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 67,
    type: "audio/mpeg",
    filePath: "/songs/13a_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 68,
    type: "audio/mpeg",
    filePath: "/songs/13a_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 69,
    type: "audio/mpeg",
    filePath: "/songs/13b_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 70,
    type: "audio/mpeg",
    filePath: "/songs/13b_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 71,
    type: "audio/mpeg",
    filePath: "/songs/13b_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 72,
    type: "audio/mpeg",
    filePath: "/songs/14_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 73,
    type: "audio/mpeg",
    filePath: "/songs/14_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 74,
    type: "audio/mpeg",
    filePath: "/songs/14_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
  {
    id: 75,
    type: "audio/mpeg",
    filePath: "/songs/15_altto.mp3",
    voiceType: 4,
    speedId: 1,
  },
  {
    id: 76,
    type: "audio/mpeg",
    filePath: "/songs/15_baritoni.mp3",
    voiceType: 2,
    speedId: 1,
  },
  {
    id: 77,
    type: "audio/mpeg",
    filePath: "/songs/15_mezzo.mp3",
    voiceType: 5,
    speedId: 1,
  },
  {
    id: 78,
    type: "audio/mpeg",
    filePath: "/songs/15_sopraano.mp3",
    voiceType: 6,
    speedId: 1,
  },
];

const songs = [
  {
    id: 1,
    title: "A Escala (Intervalos de Segunda)",
    beginning: "Manca solecitta",
    recordingIds: [1, 2, 3, 4, 5],
    lyrics:
      "Manca sollecita \n più dell´usato, \n ancor che s`agiti \n con lieve fiato, \n face che palpita \n presso al morir.",
  },
  {
    id: 2,
    title: "Intervalos de Terça",
    beginning: "Semplicetta tortorella",
    recordingIds: [6, 7, 8, 9],
    lyrics:
      "Semplicetta tortorella, \n che non vede il suo periglio, \n per fuggir dal crudo artiglio \n vola in grembo al cacciator.",
  },
  {
    id: 3,
    title: "Intervalos de Quarta",
    beginning: "Lascia il lido",
    recordingIds: [10, 11],
    lyrics:
      "Lascia il lido, e il mare infido \n a solcar torna il nocchiero, \n e pur sa che menzognero \n altre volte l'ingannò.",
  },
  {
    id: 4,
    title: "Intervalos de Quinta",
    beginning: "Avvezzo a vivere",
    recordingIds: [12, 13, 14],
    lyrics:
      "Avvezzo a vivere \n senza conforto, \n in mezzo al porto \n pavento il mar.",
  },
  {
    id: 5,
    title: "Intervalos de Sexta",
    beginning: "Bella prova é d'alma forte",
    recordingIds: [15, 16],
    lyrics:
      "Bella prova è d'alma forte \n l'esser placida e serena \n nel soffrir l'ingiusta pena \n d'una colpa, che non ha.",
  },
  {
    id: 6,
    title: "Intervalos de Sétima",
    beginning: "Fra l'ombre un lampo solo",
    recordingIds: [17, 18],
    lyrics:
      "Fra l'ombre un lampo solo \n basta al nocchier sagace \n che già ritrova il polo, \n che riconosce il mar.",
  },
  {
    id: 7,
    title: "Intervalos de Oitava",
    beginning: "Quell' onda che ruina",
    recordingIds: [19, 20],
    lyrics:
      "Quell' onda che ruina, \n balza, si frange e mormora, \n ma limpida si fa.",
  },
  {
    id: 8,
    title: "Semitons",
    beginning: "Delira dubbiosa",
    recordingIds: [21, 22, 23, 24],
    lyrics:
      "Delira dubbiosa, \n incerta, vaneggia \n ogni almache ondeggia. \n fra i moti del cor.",
  },
  {
    id: 9,
    title: "Síncope",
    beginning: "Nel contrasto amor accende",
    recordingIds: [25, 26],
    lyrics:
      "Nel contrasto amor s'accende: \n con chi cede, o chi s'arrende \n mai sì barbaro non è.",
  },
  {
    id: 10,
    title: "Introdução à Coloratura* (Introduzione alle volate)",
    beginning: "Come il candore",
    recordingIds: [27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
    lyrics:
      "Come il candore \n d'intatta neve \n è d'un bel core \n la fedeltà. \n Un' orma sola \n che in sé riceve, \n tutta ne invola \n la sua beltà.",
  },
  {
    id: 11,
    title: "Apogiaturas",
    beginning: "Senza l'amabile",
    recordingIds: [37, 38, 39, 40, 41],
    lyrics:
      "Senza l'amabile \n Dio di Citera \n i dì non tornano \n di primavera, \n non spira un zeffiro, \n non spunta un fior.\n L´erbe sul margine \n del fonte amico, \n le piante vedove \n sul colle aprico \n per lui rivestono \n l´antico onor.",
  },
  {
    id: 12,
    title: "Accacciaturas",
    beginning: "Benchè di senso privo",
    recordingIds: [42, 43, 44, 45, 46],
    lyrics:
      "Benchè di senso privo, \n fin l`arboscello è grato \n a quell'amico rivo, \n da cui riceve umor. \n per lui di fronde ornato \n bella mercè gli rende, \n dal sol quando difende \n il suo benefattor.",
  },
  {
    id: 13,
    title: "Introdução aos Mordentes",
    beginning: "La gioia verace",
    recordingIds: [47, 48, 49, 50],
    lyrics:
      "la gioja verace \n per farsi palese, \n d´un labbro loquace \n bisogno non ha.",
  },
  {
    id: 14,
    title: "Mordentes Variados",
    beginning: "L'augelletto in lacci stretto",
    recordingIds: [51, 52, 53, 54],
    lyrics:
      "L´augelletto in lacci stretto \n perchè mai cantar s´ascolta? \n Perchè spera un´ altra volta \n di tornare in libertà.",
  },
  {
    id: 15,
    title: "Introdução aos Grupetos",
    beginning: "Quando accende un nobil petto",
    recordingIds: [55, 56],
    lyrics:
      "Quando accende un nobil petto \n è innocente, è puro affetto, \n debolezza amor non è.",
  },
  {
    id: 16,
    title: "Grupetos",
    beginning: "Più non si trovano",
    recordingIds: [57, 58],
    lyrics:
      "Più non si trovano \n tra mille amanti \n sol due bell' anime \n che sian costanti, \n e tutti parlano \n di fedeltà.",
  },
  {
    id: 17,
    title: "Introdução aos Trinados* (Introduzione al trillo)",
    beginning: "Se povero il ruscello",
    recordingIds: [59, 60, 61, 62],
    lyrics:
      "Se povero il ruscello \n mormora lento e basso; \n un ramoscello, un sasso \n quasi arrestar lo fa.",
  },
  {
    id: 18,
    title: "Coloraturas* (Le volate)",
    beginning: "Siam navi all' onde algenti",
    recordingIds: [63, 64, 65],
    lyrics:
      "Siam navi all' onde algenti \n lasciate in abbandono: \n impetuosi venti \n i nostri affetti sono: \n ogni diletto è scoglio: \n tutta la vita è un mar.",
  },
  {
    id: 19,
    title: "Portamento I",
    beginning: "Vorrei spiegar l'affanno",
    recordingIds: [66, 67, 68],
    lyrics:
      "Vorrei spiegar l´affanno, \n nasconderlo vorrei; \n e mentre i dubbi miei \n così crescendo vanno, \n tutto spiegar non oso, \n tutto non so tacer. \n Sollecito, dubbioso, \n penso, rammento e vedo; \n e agli occhi miei non credo, \n non credo al mio pensier.",
  },
  {
    id: 20,
    title: "Portamento II",
    beginning: "O placido il mare",
    recordingIds: [69, 70, 71],
    lyrics:
      "O placido il mare \n lusinghi la sponda, \n o porti con l´onda \n terrore e spavento, \n è colpa del vento, \n sua colpa non è.",
  },
  {
    id: 21,
    title: "Recitativo",
    beginning: "La patria è un tutto",
    recordingIds: [72, 73, 74],
    lyrics:
      "La patria è un tutto \n di cui siam parti \n al cittadino è fallo \n considerar sè stesso \n separato da lei. \n L´utile, o il danno, \n ch'ei conoscer dee solo \n è ciò che giova \n o nuoce alla sua patria, \n a cui di tutto è debitor. \n Quando i sudori, \n e il sangue sparge per lei, \n nulla del proprio ei dona: \n rende sol ciò che n'ebbe. \n Essa il produsse, \n l'educò, lo nudrì. \n Con le sue leggi \n dagl'insulti domestici il difende, \n dagli esterni con l'armi. \n Ella gli presta nome, \n grado, ed onor; \n ne premia il merto; \n ne vendica le offese, \n e madre amante \n a fabbricar s'affanna \n la sua felicità, \n per quanto lice \n al destin de' mortali \n esser felice.",
  },
  {
    id: 22,
    title: "Recapitulação",
    beginning: "Alla stagion de' fiori",
    recordingIds: [75, 76, 77, 78],
    lyrics:
      "Alla stagion de' fiori \n e de' novelli amori \n è grato il molle fiato \n d'un zeffiro legger. \n O gema fra le fronde \n o lento increspi l'onde: \n zeffiro in ogni lato \n compagno è del piacer.",
  },
];

const skills = [
  { id: 1, title: "Intervalos" },
  { id: 2, title: "Ornamentos" },
  { id: 3, title: "Recitativos e Arias" },
];

const lessons = [
  {
    id: 1,
    title: "Vaccaj I",
    skillId: 1,
    songIds: [1, 2],
  },
  {
    id: 2,
    title: "Vaccaj II",
    skillId: 1,
    songIds: [3, 4],
  },
  {
    id: 3,
    title: "Vaccaj III",
    skillId: 1,
    songIds: [5],
  },
  {
    id: 4,
    title: "Vaccaj IV",
    skillId: 1,
    songIds: [6, 7],
  },
  {
    id: 5,
    title: "Vaccaj V",
    skillId: 2,
    songIds: [8],
  },
  {
    id: 6,
    title: "Vaccaj VI",
    skillId: 2,
    songIds: [9],
  },
  {
    id: 7,
    title: "Vaccaj VII",
    skillId: 2,
    songIds: [10],
  },
  {
    id: 8,
    title: "Vaccaj VIII",
    skillId: 2,
    songIds: [11, 12],
  },
  {
    id: 9,
    title: "Vaccaj IX",
    skillId: 2,
    songIds: [13, 14],
  },
  {
    id: 10,
    title: "Vaccaj X",
    skillId: 2,
    songIds: [15, 16],
  },
  {
    id: 11,
    title: "Vaccaj XI",
    skillId: 2,
    songIds: [17],
  },
  {
    id: 12,
    title: "Vaccaj XII",
    skillId: 2,
    songIds: [18],
  },
  {
    id: 13,
    title: "Vaccaj XIII",
    skillId: 2,
    songIds: [19, 20],
  },
  {
    id: 14,
    title: "Vaccaj XIV",
    skillId: 3,
    songIds: [21],
  },
  {
    id: 15,
    title: "Vaccaj XV",
    skillId: 3,
    songIds: [22],
  },
];

export {
  voiceTypes,
  voiceTypeOrderById,
  speeds,
  recordings,
  songs,
  skills,
  lessons,
};
